'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { useForm } from 'react-hook-form';
import { supabase } from '@/lib/supabase';
import Navbar from '@/components/Navbar';
import { QRCodeCanvas } from 'qrcode.react';

interface MaterialForm {
  type: string;            // Matches DB schema
  customer_name: string;   // Matches DB schema
  customer_contact: string; // Matches DB schema
  // qr_code is generated by the system
  // No description field in DB schema
}

export default function NewMaterial() {
  const router = useRouter();
  const { register, handleSubmit, formState: { errors } } = useForm<MaterialForm>();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);
  const [materialId, setMaterialId] = useState<string | null>(null);
  
  const onSubmit = async (data: MaterialForm) => {
    setLoading(true);
    setError(null);
    
    try {
      // Map form fields to DB column names - exactly matching the schema
      const newMaterial = {
        type: data.type,
        customer_name: data.customer_name,
        customer_contact: data.customer_contact,
        // Generate a unique QR code - using UUID v4
        qr_code: crypto.randomUUID(), 
        current_stage: 'received',
        status: 'pending',
        received_date: new Date().toISOString(),
      };
      
      const { data: material, error } = await supabase
        .from('materials')
        .insert(newMaterial)
        .select()
        .single();
      
      if (error) throw error;
      
      setMaterialId(material.id);
      setSuccess(true);
    } catch (err: any) {
      console.error('Error creating material:', err);
      setError(err.message || 'An error occurred while registering the material.');
    } finally {
      setLoading(false);
    }
  };

  const materialTypes = [
    'Cement',
    'Steel',
    'Concrete',
    'Aggregate',
    'Brick',
    'Sand',
    'Soil',
    'Asphalt',
    'Other'
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      
      <div className="container mx-auto px-4 py-8">
        <div className="mb-6">
          <Link href="/dashboard" className="text-indigo-600 hover:text-indigo-800">
            &larr; Back to Dashboard
          </Link>
        </div>
        
        <div className="bg-white shadow-sm rounded-lg p-6">
          <h1 className="text-2xl font-bold text-gray-900 mb-6">Register New Material</h1>
          
          {success && materialId ? (
            <div className="text-center">
              <div className="bg-green-50 border-l-4 border-green-500 p-4 mb-6">
                <p className="text-green-700">Material registered successfully!</p>
              </div>
              
              <div className="mb-6">
                <h2 className="text-lg font-medium text-gray-900 mb-4">Material QR Code</h2>
                <div className="inline-block bg-white p-4 rounded-md shadow-sm">
                  <QRCodeCanvas 
                    value={`${typeof window !== 'undefined' ? window.location.origin : ''}/material/${materialId}`} 
                    size={200} 
                  />
                </div>
                <p className="mt-4 text-sm text-gray-500">Scan this QR code to access material details</p>
              </div>
              
              <div className="flex justify-center space-x-4">
                <Link
                  href={`/material/${materialId}`}
                  className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-md shadow-sm text-sm font-medium transition"
                >
                  View Material Details
                </Link>
                
                <button
                  onClick={() => {
                    setSuccess(false);
                    setMaterialId(null);
                  }}
                  className="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 rounded-md shadow-sm text-sm font-medium transition"
                >
                  Register Another Material
                </button>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
              {error && (
                <div className="bg-red-50 border-l-4 border-red-500 p-4 mb-4">
                  <p className="text-red-700">{error}</p>
                </div>
              )}
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label htmlFor="type" className="block text-sm font-medium text-gray-700 mb-1">
                    Material Type *
                  </label>
                  <select
                    id="type"
                    className="appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    {...register('type', { required: 'Material type is required' })}
                  >
                    <option value="">Select Material Type</option>
                    {materialTypes.map((type) => (
                      <option key={type} value={type}>{type}</option>
                    ))}
                  </select>
                  {errors.type && (
                    <p className="mt-1 text-sm text-red-600">{errors.type.message}</p>
                  )}
                </div>
                
                {/* Removed description field as it's not in the database schema */}
                
                <div>
                  <label htmlFor="customer_name" className="block text-sm font-medium text-gray-700 mb-1">
                    Customer Name *
                  </label>
                  <input
                    id="customer_name"
                    type="text"
                    className="appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    placeholder="Customer name"
                    {...register('customer_name', { required: 'Customer name is required' })}
                  />
                  {errors.customer_name && (
                    <p className="mt-1 text-sm text-red-600">{errors.customer_name.message}</p>
                  )}
                </div>
                
                <div>
                  <label htmlFor="customer_contact" className="block text-sm font-medium text-gray-700 mb-1">
                    Customer Contact *
                  </label>
                  <input
                    id="customer_contact"
                    type="text"
                    className="appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                    placeholder="Email or phone number"
                    {...register('customer_contact', {
                      required: 'Customer contact is required'
                    })}
                  />
                  {errors.customer_contact && (
                    <p className="mt-1 text-sm text-red-600">{errors.customer_contact.message}</p>
                  )}
                </div>
              </div>
              
              <div className="flex justify-end">
                <Link
                  href="/dashboard"
                  className="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 rounded-md shadow-sm text-sm font-medium transition mr-3"
                >
                  Cancel
                </Link>
                
                <button
                  type="submit"
                  disabled={loading}
                  className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-md shadow-sm text-sm font-medium transition disabled:bg-indigo-400"
                >
                  {loading ? 'Registering...' : 'Register Material'}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}